name: Run Copilot Survey on Issue Creation

on:
  issues:
    types: [opened, labeled]

permissions:
  id-token: write
  contents: read

jobs:
  run-copilot-survey:
    if: contains(github.event.issue.labels.*.name, 'copilot-survey')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Get 'copilot-survey' label
      id: get-label
      run: |
        LABEL_NAME=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[] | select(.name=="copilot-survey") | .name')
        echo "LABEL_NAME=$LABEL_NAME" >> $GITHUB_ENV

    - name: Run fetch-copilot-survey.py
      run: python fetch-copilot-survey.py -token ${{ secrets.GITHUB_TOKEN }} -org ${{ github.repository_owner }} -label $LABEL_NAME

    - name: Comment on issue
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const path = 'pull_requests.xlsx';
          const content = fs.readFileSync(path, {encoding: 'base64'});

          github.rest.repos.createOrUpdateFileContents({
            owner,
            repo,
            path,
            message: 'uploading pull_requests.xlsx',
            content,
            issue_number
          });