name: Run Copilot Survey on Issue Creation

on:
  issues:
    types: [labeled]

permissions:
  id-token: write
  contents: read

jobs:
  run-copilot-survey:
    if: contains(github.event.issue.labels.*.name, 'copilot-survey')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Get 'copilot-survey' label
      id: get-label
      run: |
        LABEL_NAME=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[] | select(.name=="copilot-survey") | .name')
        echo "LABEL_NAME=$LABEL_NAME" >> $GITHUB_ENV

    - name: Run fetch_survey.py
      run: python fetch_survey.py --token ${{ secrets.GITHUB_TOKEN_WITH_ENOUGH_PERMISSION }} --org ${{ github.repository_owner }} --label ${{ env.LABEL_NAME }}

    - name: Upload Excel file
      uses: actions/upload-artifact@v2
      with:
        name: pull_requests
        path: ./pull_requests.xlsx

    - name: Comment on issue with artifact URL
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN_WITH_ENOUGH_PERMISSION}}
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const run_id = context.runId;
          const comment = `You can download the artifact from [here](https://github.com/${owner}/${repo}/actions/runs/${run_id})`;
          github.rest.issues.createComment({
            owner: owner,
            repo: repo,
            issue_number: issue_number,
            body: comment
          });