name: Run Copilot Survey on Issue Creation

on:
  issues:
    types: [opened, labeled]

jobs:
  run-copilot-survey:
    if: contains(github.event.issue.labels.*.name, 'copilot-survey')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run fetch-copilot-survey.py
      run: python fetch-copilot-survey.py

    - name: Upload pull_requests.xlsx to issue
      uses: actions/upload-artifact@v2
      with:
        name: pull_requests.xlsx
        path: pull_requests.xlsx