name: Run Copilot Survey And Upload To S3

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

#install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas openpyxl

# Run the python file
    - name: Run fetch-copilot-survey.py
      run: python fetch-copilot-survey.py

# configure AWS OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume:<aws role arn>:role/<role name>
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}}

# copy generated excel to S3 bucket
    - name: Copy excel to S3 bucket
      run: aws s3 cp ./pull_requests.xlsx s3://my-bucket/output.csv